#!/bin/bash
# WARNING: this script will destroy data on the selected disk.
# This script can be run by executing the following:
#   curl -sL https://git.io/fhiYQ | bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

### Get infomation from user ###
hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
clear
: ${hostname:?"hostname cannot be empty"}

user=$(dialog --stdout --inputbox "Enter admin username" 0 0) || exit 1
clear
: ${user:?"user cannot be empty"}

full_name=$(dialog --stdout --inputbox "Enter admin full name" 0 0) || exit 1
clear
: ${full_name:?"full name cannot be empty"}

password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
clear
: ${password:?"password cannot be empty"}
password2=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
clear
[[ "$password" == "$password2" ]] || ( echo "Passwords did not match"; exit 1; )

devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
device=$(dialog --stdout --menu "Select installation disk" 0 0 0 ${devicelist}) || exit 1
clear

REPO_URL="https://github.com/osafi/aur/releases/download/repository"
MIRRORLIST_URL="https://www.archlinux.org/mirrorlist/?country=US&protocol=https&use_mirror_status=on"

# Update keyring for pacman
pacman -Sy --noconfirm archlinux-keyring

# Install pacman-contrib for the 'rankmirrors' command
pacman -Sy --noconfirm pacman-contrib

echo "Updating mirror list"
curl -s "$MIRRORLIST_URL" | \
    sed -e 's/^#Server/Server/' -e '/^#/d' | \
    rankmirrors -n 5 - > /etc/pacman.d/mirrorlist

### Set up logging ###
exec 1> >(tee "stdout.log")
exec 2> >(tee "stderr.log")

timedatectl set-ntp true

### Setup the disk and partitions ###
boot_start=1
boot_end=$(( $boot_start + 128 ))

swap_size=$(free --mebi | awk '/Mem:/ {print $2}')
swap_start=$boot_end
swap_end=$(( $swap_start + $swap_size ))

reco_start=$swap_end
reco_end=$(( $reco_start + 1024 ))

parted --script "${device}" -- mklabel gpt \
  mkpart ESP fat32 ${boot_start}MiB ${boot_end}MiB \
  set 1 boot on \
  mkpart primary linux-swap ${swap_start}MiB ${swap_end}MiB \
  mkpart primary ext4 ${reco_start}MiB ${reco_end}MiB \
  name 3 'Recovery' \
  mkpart primary ext4 ${reco_end}MiB 100%

part_boot="$(ls ${device}* | grep -E "^${device}p?1$")"
part_swap="$(ls ${device}* | grep -E "^${device}p?2$")"
part_reco="$(ls ${device}* | grep -E "^${device}p?3$")"
part_root="$(ls ${device}* | grep -E "^${device}p?4$")"

wipefs "${part_boot}"
wipefs "${part_swap}"
wipefs "${part_reco}"
wipefs "${part_root}"

mkfs.vfat -F32 "${part_boot}"
mkswap "${part_swap}"
mkfs.ext4 "${part_reco}"
mkfs.f2fs -f "${part_root}"

swapon "${part_swap}"
mkdir /recovery
mount "${part_reco}" /recovery
mount "${part_root}" /mnt
mkdir /mnt/boot
mount "${part_boot}" /mnt/boot

### Install and configure the basic system ###
cat >>/etc/pacman.conf <<EOF
[aur]
SigLevel = Optional TrustAll
Server = $REPO_URL
EOF

# pacstrap /mnt osafi-dell-xps refind-efi parted
pacstrap /mnt base grub efibootmgr os-prober intel-ucode zsh
genfstab -t PARTUUID /mnt >> /mnt/etc/fstab
echo "${hostname}" > /mnt/etc/hostname

cat >>/mnt/etc/pacman.conf <<EOF
[aur]
SigLevel = Optional TrustAll
Server = $REPO_URL
EOF

# arch-chroot /mnt bootctl install

# cat <<EOF > /mnt/boot/loader/loader.conf
# default arch
# EOF

# cat <<EOF > /mnt/boot/loader/entries/arch.conf
# title    Arch Linux
# linux    /vmlinuz-linux
# initrd   /intel-ucode.img
# initrd   /initramfs-linux.img
# options  root=PARTUUID=$(blkid -s PARTUUID -o value "$part_root") rw
# EOF

# cat <<EOF > /mnt/boot/loader/entries/archiso.conf
# title    Arch Linux UEFI Live CD
# linux    /archiso/boot/x86_64/vmlinuz
# initrd   /archiso/boot/intel_ucode.img
# initrd   /archiso/boot/amd_ucode.img
# initrd   /archiso/boot/x86_64/archiso.img
# options  archisodevice=${part_reco} archisobasedir=archiso archisolabel=ARCH_201904 copytoram
# EOF

# TODO: find a way to get files without redownloading iso?
#curl -L -o /mnt/archlinux.iso https://mirrors.edge.kernel.org/archlinux/iso/2019.04.01/archlinux-2019.04.01-x86_64.iso
# curl -L -o /mnt/archlinux.iso http://192.168.0.105/archlinux-2018.09.01-x86_64.iso

arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --removable
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

arch-chroot /mnt useradd -mU -s /bin/zsh -c "$full_name" -G wheel,uucp,video,audio,storage,games,input "$user"

echo "$user:$password" | chpasswd --root /mnt
echo "root:$password" | chpasswd --root /mnt

arch-chroot /mnt chsh -s /bin/zsh

umount /recovery
umount -R /mnt