#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "polybar" layer=above

feh --bg-fill /usr/share/backgrounds/osafi/wallpaper.png

/etc/osafi/polybar/launcher.sh
nm-applet &
sxhkd -c /etc/osafi/sxhkd/sxhkdrc &
