#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a "polybar" layer=above

nm-applet &

for i in $(find "/etc/osafi/initrc.d/" -iname "*.sh")
do
  source "$i"
done