#!/bin/bash

set -ex

# Variables declaration.
declare -r pkgrepo="${1#*/}"

for package in pkg/* ; do
	pushd "$package"
	makepkg -CcfsA --noconfirm
	mv *.pkg.tar.xz ~/bin/
	popd
done

pushd bin
repo-add "${pkgrepo}.db.tar.gz" *.pkg.tar.xz
popd

{ set +ex; } 2>/dev/null
