#!/bin/bash

set -ex

# Variables declaration.
declare -r pkgrepo="${1#*/}"
declare -r repodir="$(pwd)/bin"
declare -r repodb="${repodir}/${pkgrepo}.db.tar.gz"

for package in pkg/* ; do
	pushd "$package"
	makepkg --ignorearche --cleanbuild --clean --syncdeps --rmdeps --noconfirm --force
	mv *.pkg.tar.xz "${repodir}"
	popd
done

pushd bin
repo-add "${repodb}" *.pkg.tar.xz
popd

{ set +ex; } 2>/dev/null
