name: Build ArchLinux Package Repository

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch: # Enables the manual 'Run Workflow' button in GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osafi/arch-pkg-builder
    steps:
      - name: Setup workspace
        run: |
             sudo mkdir -p $GITHUB_WORKSPACE
             sudo mkdir -p $GITHUB_WORKSPACE/_temp
             sudo chown -R builder:builder $GITHUB_WORKSPACE
             sudo mkdir -p $HOME
             sudo chown -R builder:builder $HOME

      - uses: actions/checkout@v3
        name: Checkout

      - name: Sync remote repo
        run: ./scripts/sync-remote-repo ${GITHUB_REPOSITORY} repository
        
      - name: Build AUR packages
        run: ./scripts/build-aur ${GITHUB_REPOSITORY}
      
      - name: Build packages
        run: ./scripts/build-pkg ${GITHUB_REPOSITORY}

      - name: Upload packages to release
        uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ./bin/*.+(db|files|gz|zst)
          tag: repository
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup old packages
        run: python ./scripts/clean-remote-repo ${{ secrets.ACCESS_TOKEN_GITHUB }} ${GITHUB_REPOSITORY} repository
